/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/accreg/': RouteRecordInfo<
      '/accreg/',
      '/accreg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/active-sessions/': RouteRecordInfo<
      '/active-sessions/',
      '/active-sessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/active-sessions/row-actions': RouteRecordInfo<
      '/active-sessions/row-actions',
      '/active-sessions/row-actions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/all-sessions/': RouteRecordInfo<
      '/all-sessions/',
      '/all-sessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/audit-logs/': RouteRecordInfo<
      '/audit-logs/',
      '/audit-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/'
      | '/auth/forgot-password'
      | '/auth/otp'
      | '/auth/sign-in'
      | '/auth/sign-in-2'
      | '/auth/sign-up'
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/otp': RouteRecordInfo<
      '/auth/otp',
      '/auth/otp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in': RouteRecordInfo<
      '/auth/sign-in',
      '/auth/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in-2': RouteRecordInfo<
      '/auth/sign-in-2',
      '/auth/sign-in-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-up': RouteRecordInfo<
      '/auth/sign-up',
      '/auth/sign-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/basis-protocol/': RouteRecordInfo<
      '/basis-protocol/',
      '/basis-protocol',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/code-mkb/': RouteRecordInfo<
      '/code-mkb/',
      '/code-mkb',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dialyzers/': RouteRecordInfo<
      '/dialyzers/',
      '/dialyzers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee-positions/': RouteRecordInfo<
      '/employee-positions/',
      '/employee-positions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee-tenant/': RouteRecordInfo<
      '/employee-tenant/',
      '/employee-tenant',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors': RouteRecordInfo<
      '/errors',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | '/errors/'
      | '/errors/401'
      | '/errors/403'
      | '/errors/404'
      | '/errors/500'
      | '/errors/503'
    >,
    '/errors/': RouteRecordInfo<
      '/errors/',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/401': RouteRecordInfo<
      '/errors/401',
      '/errors/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/403': RouteRecordInfo<
      '/errors/403',
      '/errors/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/404': RouteRecordInfo<
      '/errors/404',
      '/errors/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/500': RouteRecordInfo<
      '/errors/500',
      '/errors/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/503': RouteRecordInfo<
      '/errors/503',
      '/errors/503',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/finished-sessions/': RouteRecordInfo<
      '/finished-sessions/',
      '/finished-sessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/finished-sessions/row-actions': RouteRecordInfo<
      '/finished-sessions/row-actions',
      '/finished-sessions/row-actions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/machines/': RouteRecordInfo<
      '/machines/',
      '/machines',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/med-cards/': RouteRecordInfo<
      '/med-cards/',
      '/med-cards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/med-cards/[id]': RouteRecordInfo<
      '/med-cards/[id]',
      '/med-cards/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/medical-types/': RouteRecordInfo<
      '/medical-types/',
      '/medical-types',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/patients/': RouteRecordInfo<
      '/patients/',
      '/patients',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/patients/patient-editor-popup': RouteRecordInfo<
      '/patients/patient-editor-popup',
      '/patients/patient-editor-popup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/patients/patient-row-actions': RouteRecordInfo<
      '/patients/patient-row-actions',
      '/patients/patient-row-actions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/protocol-add': RouteRecordInfo<
      '/protocol-add',
      '/protocol-add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/protocols/': RouteRecordInfo<
      '/protocols/',
      '/protocols',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/protocols/[id]': RouteRecordInfo<
      '/protocols/[id]',
      '/protocols/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/protocols/protocol-row-actions': RouteRecordInfo<
      '/protocols/protocol-row-actions',
      '/protocols/protocol-row-actions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reasons/': RouteRecordInfo<
      '/reasons/',
      '/reasons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sessions/session-row-actions': RouteRecordInfo<
      '/sessions/session-row-actions',
      '/sessions/session-row-actions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account': RouteRecordInfo<
      '/settings/account',
      '/settings/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/appearance': RouteRecordInfo<
      '/settings/appearance',
      '/settings/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/display': RouteRecordInfo<
      '/settings/display',
      '/settings/display',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/notifications': RouteRecordInfo<
      '/settings/notifications',
      '/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tenants/': RouteRecordInfo<
      '/tenants/',
      '/tenants',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/': RouteRecordInfo<
      '/users/',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/[id]': RouteRecordInfo<
      '/users/[id]',
      '/users/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/users/user-row-actions': RouteRecordInfo<
      '/users/user-row-actions',
      '/users/user-row-actions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/accreg/index.vue': {
      routes:
        | '/accreg/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/active-sessions/index.vue': {
      routes:
        | '/active-sessions/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/active-sessions/row-actions.vue': {
      routes:
        | '/active-sessions/row-actions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/all-sessions/index.vue': {
      routes:
        | '/all-sessions/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/audit-logs/index.vue': {
      routes:
        | '/audit-logs/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/'
        | '/auth/forgot-password'
        | '/auth/otp'
        | '/auth/sign-in'
        | '/auth/sign-in-2'
        | '/auth/sign-up'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/otp.vue': {
      routes:
        | '/auth/otp'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/sign-in.vue': {
      routes:
        | '/auth/sign-in'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/sign-in-2.vue': {
      routes:
        | '/auth/sign-in-2'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/sign-up.vue': {
      routes:
        | '/auth/sign-up'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/basis-protocol/index.vue': {
      routes:
        | '/basis-protocol/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/code-mkb/index.vue': {
      routes:
        | '/code-mkb/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dialyzers/index.vue': {
      routes:
        | '/dialyzers/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/employee-positions/index.vue': {
      routes:
        | '/employee-positions/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/employee-tenant/index.vue': {
      routes:
        | '/employee-tenant/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors.vue': {
      routes:
        | '/errors'
        | '/errors/'
        | '/errors/401'
        | '/errors/403'
        | '/errors/404'
        | '/errors/500'
        | '/errors/503'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/errors/index.vue': {
      routes:
        | '/errors/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/401.vue': {
      routes:
        | '/errors/401'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/403.vue': {
      routes:
        | '/errors/403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/404.vue': {
      routes:
        | '/errors/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/500.vue': {
      routes:
        | '/errors/500'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/errors/503.vue': {
      routes:
        | '/errors/503'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/finished-sessions/index.vue': {
      routes:
        | '/finished-sessions/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/finished-sessions/row-actions.vue': {
      routes:
        | '/finished-sessions/row-actions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/machines/index.vue': {
      routes:
        | '/machines/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/med-cards/index.vue': {
      routes:
        | '/med-cards/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/med-cards/[id].vue': {
      routes:
        | '/med-cards/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/medical-types/index.vue': {
      routes:
        | '/medical-types/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/patients/index.vue': {
      routes:
        | '/patients/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/patients/patient-editor-popup.vue': {
      routes:
        | '/patients/patient-editor-popup'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/patients/patient-row-actions.vue': {
      routes:
        | '/patients/patient-row-actions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/protocol-add.vue': {
      routes:
        | '/protocol-add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/protocols/index.vue': {
      routes:
        | '/protocols/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/protocols/[id].vue': {
      routes:
        | '/protocols/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/protocols/protocol-row-actions.vue': {
      routes:
        | '/protocols/protocol-row-actions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reasons/index.vue': {
      routes:
        | '/reasons/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/sessions/session-row-actions.vue': {
      routes:
        | '/sessions/session-row-actions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/account.vue': {
      routes:
        | '/settings/account'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/appearance.vue': {
      routes:
        | '/settings/appearance'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/display.vue': {
      routes:
        | '/settings/display'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/notifications.vue': {
      routes:
        | '/settings/notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tenants/index.vue': {
      routes:
        | '/tenants/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/users/index.vue': {
      routes:
        | '/users/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/users/[id].vue': {
      routes:
        | '/users/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/users/user-row-actions.vue': {
      routes:
        | '/users/user-row-actions'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
